version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8000"

  vue-project:
    build: ./vue-project
    volumes:
      - './vue-project:/app'
      - '/app/node_modules'
    ports:
      - "8080:80"